# -*- coding: utf-8 -*-
"""LLM-Arena-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfrXJHBSrm8AsZBvAr3U8z56HXDVYXVj
"""

import json
import re
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional
import pandas as pd
from IPython.display import display, Markdown, HTML

# Configuration - update this path as needed
TOURNAMENT_PATH = Path("logs/round-robin-2026-01-27-1056")

# Data structures

@dataclass
class Turn:
    """A single turn from a player's perspective."""
    turn_num: int
    observation: str
    state: str
    action: Optional[str]
    reasoning: Optional[str]
    prediction: Optional[str]
    confidence: Optional[int]  # 0-100
    tool_calls: list[dict]
    tokens: dict  # input, output, reasoning
    latency_ms: int
    raw_response: str

@dataclass
class PlayerLog:
    """All turns from one player in a match."""
    player_id: str
    model: str
    team: str
    turns: list[Turn]

@dataclass
class ProtocolEvent:
    """A single event from the battle protocol."""
    turn: int
    event_type: str
    args: list

@dataclass
class Match:
    """A complete match with all data."""
    match_id: int
    battle_id: str
    model_a: str
    model_b: str
    team_a: str
    team_b: str
    winner: Optional[str]
    total_turns: int
    protocol: list[ProtocolEvent]
    player_logs: dict[str, PlayerLog]  # player_id -> log
    metadata: dict

@dataclass
class Tournament:
    """Complete tournament data."""
    name: str
    format: str
    models: list[str]
    games_per_pair: int
    matches: list[Match]
    manifest: dict

# Parsing utilities

def extract_thinking(raw_response: str) -> Optional[str]:
    """Extract content from <thinking> blocks."""
    pattern = r'<thinking>(.*?)</thinking>'
    matches = re.findall(pattern, raw_response, re.DOTALL)
    return '\n---\n'.join(matches) if matches else None

def parse_confidence(conf_str: Optional[str]) -> Optional[int]:
    """Parse confidence string like '75%' or '** 75' to int."""
    if not conf_str:
        return None
    # Remove common prefixes like '** '
    cleaned = re.sub(r'^[\*\s]+', '', str(conf_str))
    # Extract digits
    match = re.search(r'(\d+)', cleaned)
    return int(match.group(1)) if match else None

def parse_player_log(path: Path, metadata: dict) -> PlayerLog:
    """Parse a player's JSONL log file."""
    player_id = path.stem
    player_info = metadata.get('players', {}).get(player_id, {})

    turns = []
    with open(path) as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            parsed = data.get('parsed', {})

            turn = Turn(
                turn_num=data.get('turn', 0),
                observation=data.get('observation', ''),
                state=data.get('state', ''),
                action=parsed.get('action'),
                reasoning=extract_thinking(data.get('raw_response', '')),
                prediction=parsed.get('prediction'),
                confidence=parse_confidence(data.get('confidence')),
                tool_calls=data.get('tool_calls', []),
                tokens=data.get('tokens', {}),
                latency_ms=data.get('latency_ms', 0),
                raw_response=data.get('raw_response', '')
            )
            turns.append(turn)

    return PlayerLog(
        player_id=player_id,
        model=player_info.get('model', 'unknown'),
        team=player_info.get('team', 'unknown'),
        turns=turns
    )

def parse_protocol(path: Path) -> list[ProtocolEvent]:
    """Parse protocol.jsonl into structured events."""
    events = []
    with open(path) as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            turn = data.get('turn', 0)
            for event in data.get('events', []):
                if len(event) >= 2:
                    events.append(ProtocolEvent(
                        turn=turn,
                        event_type=event[1] if event[1] else 'empty',
                        args=event[2:] if len(event) > 2 else []
                    ))
    return events

def load_match(match_dir: Path, manifest_match: dict) -> Match:
    """Load a complete match from its directory."""
    metadata_path = match_dir / 'metadata.json'
    protocol_path = match_dir / 'protocol.jsonl'

    with open(metadata_path) as f:
        metadata = json.load(f)

    protocol = parse_protocol(protocol_path) if protocol_path.exists() else []

    # Load player logs
    player_logs = {}
    for p in match_dir.glob('*.jsonl'):
        if p.name != 'protocol.jsonl':
            log = parse_player_log(p, metadata)
            player_logs[log.player_id] = log

    outcome = metadata.get('outcome', {})

    return Match(
        match_id=manifest_match['id'],
        battle_id=metadata.get('battle_id', ''),
        model_a=manifest_match['model_a'],
        model_b=manifest_match['model_b'],
        team_a=manifest_match['team_a'],
        team_b=manifest_match['team_b'],
        winner=manifest_match.get('winner'),
        total_turns=outcome.get('total_turns', 0),
        protocol=protocol,
        player_logs=player_logs,
        metadata=metadata
    )

def load_tournament(path: Path) -> Tournament:
    """Load complete tournament data."""
    manifest_path = path / 'manifest.json'
    with open(manifest_path) as f:
        manifest = json.load(f)

    tourney_info = manifest['tournament']
    matches = []

    for m in manifest['matches']:
        match_dir = path / f"match-{m['id']:04d}"
        if match_dir.exists():
            matches.append(load_match(match_dir, m))

    return Tournament(
        name=tourney_info['name'],
        format=tourney_info['format'],
        models=tourney_info['models'],
        games_per_pair=tourney_info['games_per_pair'],
        matches=matches,
        manifest=manifest
    )

# Load the tournament
tournament = load_tournament(TOURNAMENT_PATH)
print(f"Loaded tournament: {tournament.name}")
print(f"Format: {tournament.format}")
print(f"Models: {', '.join(tournament.models)}")
print(f"Matches: {len(tournament.matches)}")

# Match summary table
match_data = []
for m in tournament.matches:
    match_data.append({
        'Match': m.match_id,
        'Model A': m.model_a,
        'Model B': m.model_b,
        'Winner': m.winner or 'N/A',
        'Turns': m.total_turns,
        'Team A': m.team_a,
        'Team B': m.team_b
    })

df_matches = pd.DataFrame(match_data)
display(df_matches)

# Win rates
def compute_win_rates(tournament: Tournament) -> pd.DataFrame:
    """Compute overall and head-to-head win rates."""
    wins = {m: 0 for m in tournament.models}
    games = {m: 0 for m in tournament.models}

    for match in tournament.matches:
        games[match.model_a] += 1
        games[match.model_b] += 1
        if match.winner:
            wins[match.winner] += 1

    data = []
    for model in tournament.models:
        rate = wins[model] / games[model] * 100 if games[model] > 0 else 0
        data.append({
            'Model': model,
            'Wins': wins[model],
            'Games': games[model],
            'Win Rate': f"{rate:.1f}%"
        })

    return pd.DataFrame(data)

display(Markdown("### Overall Win Rates"))
display(compute_win_rates(tournament))

# Head-to-head matrix
def head_to_head(tournament: Tournament) -> pd.DataFrame:
    """Create head-to-head win matrix."""
    models = tournament.models
    matrix = {m: {n: 0 for n in models} for m in models}

    for match in tournament.matches:
        if match.winner:
            loser = match.model_b if match.winner == match.model_a else match.model_a
            matrix[match.winner][loser] += 1

    df = pd.DataFrame(matrix).T
    df.index.name = 'Winner ↓ / Loser →'
    return df

display(Markdown("### Head-to-Head Wins"))
display(head_to_head(tournament))

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Flatten the match data into a per-player-per-match format
plot_records = []
for match in tournament.matches:
    # Entry for Model A
    plot_records.append({
        'Model': match.model_a,
        'Turns': match.total_turns,
        'Outcome': 'Win' if match.winner == match.model_a else 'Loss'
    })
    # Entry for Model B
    plot_records.append({
        'Model': match.model_b,
        'Turns': match.total_turns,
        'Outcome': 'Win' if match.winner == match.model_b else 'Loss'
    })

df_plot = pd.DataFrame(plot_records)

# 2. Create the visualization
plt.figure(figsize=(12, 6))
sns.set_theme(style="whitegrid")

# Main boxplot to show distribution
sns.boxplot(
    data=df_plot,
    x='Model',
    y='Turns',
    hue='Outcome',
    order=tournament.models,
    palette={'Win': '#4CAF50', 'Loss': '#F44336'}, # Green for Win, Red for Loss
    fliersize=0 # Hide boxplot outliers to avoid overlapping with stripplot points
)

# Overlap individual points to show specific matches
sns.stripplot(
    data=df_plot,
    x='Model',
    y='Turns',
    hue='Outcome',
    order=tournament.models,
    dodge=True,
    marker='o',
    alpha=0.4,
    jitter=True,
    palette={'Win': 'black', 'Loss': 'black'}, # Keeping points black for visibility on colored boxes
    legend=False
)

plt.title('Match Length (Turns) Distribution by Model and Outcome', fontsize=14)
plt.ylabel('Total Turns')
plt.xlabel('Model')
plt.legend(title='Outcome', loc='upper right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Extract confidence history for all models
conf_history = []
for match in tournament.matches:
    for player_id, log in match.player_logs.items():
        # Identify model name and outcome
        model_name = log.model
        # Standardize model name if it's a full path
        for m in tournament.models:
            if m.lower() in model_name.lower():
                model_name = m
                break

        outcome = 'Win' if match.winner == model_name else 'Loss'

        for turn in log.turns:
            if turn.confidence is not None:
                conf_history.append({
                    'Match ID': match.match_id,
                    'Model': model_name,
                    'Turn': turn.turn_num,
                    'Confidence': turn.confidence,
                    'Outcome': outcome
                })

df_conf = pd.DataFrame(conf_history)

# 2. Create subplots for each model
num_models = len(tournament.models)
fig, axes = plt.subplots(num_models, 1, figsize=(12, 4 * num_models), sharex=True, sharey=True)
if num_models == 1: axes = [axes]

sns.set_theme(style="whitegrid")
palette = {'Win': '#4CAF50', 'Loss': '#F44336'}

for i, model in enumerate(tournament.models):
    ax = axes[i]
    model_data = df_conf[df_conf['Model'] == model]

    if model_data.empty:
        ax.text(0.5, 0.5, f"No confidence data for {model}", ha='center')
        continue

    # Plot individual lines for each match
    sns.lineplot(
        data=model_data,
        x='Turn',
        y='Confidence',
        hue='Outcome',
        units='Match ID',
        estimator=None,
        ax=ax,
        palette=palette,
        alpha=0.6,
        linewidth=1.5
    )

    ax.set_title(f'Confidence Evolution: {model}', fontsize=14, fontweight='bold')
    ax.set_ylabel('Confidence (%)')
    ax.set_ylim(-5, 105)
    ax.legend(title='Outcome', loc='lower right')

plt.xlabel('Turn Number')
plt.tight_layout()
plt.show()



import seaborn as sns
import matplotlib.pyplot as plt

# Tool usage patterns
def tool_usage_stats(tournament: Tournament):
    """Analyze which tools each model uses and how often."""
    from collections import defaultdict

    tool_counts = defaultdict(lambda: defaultdict(int))
    turn_counts = defaultdict(int)

    for match in tournament.matches:
        for player_id, log in match.player_logs.items():
            # Match model name
            model = None
            for m in tournament.models:
                if m.lower().replace('-', '') in player_id.lower().replace('-', ''):
                    model = m
                    break
            if not model:
                continue

            for turn in log.turns:
                turn_counts[model] += 1
                for tc in turn.tool_calls:
                    tool_name = tc.get('name', 'unknown')
                    tool_counts[model][tool_name] += 1

    # Get all tool names
    all_tools = sorted(list(set(tool for counts in tool_counts.values() for tool in counts)))

    display_data = []
    heatmap_data = []

    for model in tournament.models:
        row = {'Model': model, 'Turns': turn_counts[model]}
        h_row = {'Model': model}
        for tool in all_tools:
            count = tool_counts[model].get(tool, 0)
            per_turn = count / turn_counts[model] if turn_counts[model] > 0 else 0
            row[tool] = f"{count} ({per_turn:.2f}/turn)"
            h_row[tool] = per_turn
        display_data.append(row)
        heatmap_data.append(h_row)

    return pd.DataFrame(display_data), pd.DataFrame(heatmap_data)

display(Markdown("### Tool Usage Analysis"))
df_tools, df_tools_numeric = tool_usage_stats(tournament)

# Display table
display(df_tools)

# Display Heatmap
plt.figure(figsize=(14, 6))
sns.set_theme(style="white")

# Pivot for heatmap
plot_df = df_tools_numeric.set_index('Model')

sns.heatmap(
    plot_df,
    annot=True,
    fmt=".2f",
    cmap="YlGnBu",
    linewidths=.5,
    cbar_kws={'label': 'Calls per Turn'}
)

plt.title('Tool Usage Frequency by Model (Mean Calls/Turn)', fontsize=14, fontweight='bold')
plt.xlabel('Tool Name')
plt.ylabel('Model')
plt.tight_layout()
plt.show()


# === Switching and Survival Metrics ===

# Track per-match stats for each model
switch_data = {m: {'switches_per_match': [], 'turns_per_match': []} for m in tournament.models}
survival_data = {m: [] for m in tournament.models}  # Pokemon remaining in wins

for match in tournament.matches:
    # 1. Calculate switches per model in this match
    for player_id, log in match.player_logs.items():
        # Identify model from player_id
        model = None
        for m in tournament.models:
            if m.lower().replace('-', '') in player_id.lower().replace('-', ''):
                model = m
                break
        if not model:
            continue

        match_switches = 0
        match_turns = len(log.turns)
        for turn in log.turns:
            if turn.action and turn.action.startswith('switch '):
                match_switches += 1

        switch_data[model]['switches_per_match'].append(match_switches)
        switch_data[model]['turns_per_match'].append(match_turns)

    # 2. Calculate surviving Pokemon for the winner
    if match.winner:
        # Count faints for each side from protocol
        p1_faints = 0
        p2_faints = 0
        for event in match.protocol:
            if event.event_type == 'faint' and event.args:
                poke_str = str(event.args[0])
                if poke_str.startswith('p1'):
                    p1_faints += 1
                elif poke_str.startswith('p2'):
                    p2_faints += 1

        # Determine which side the winner was on
        # model_a is always p1, model_b is always p2
        if match.winner == match.model_a:
            winner_faints = p1_faints
        else:
            winner_faints = p2_faints

        surviving = 6 - winner_faints
        survival_data[match.winner].append(surviving)

# Aggregate results
results = []
for model in tournament.models:
    all_switches = switch_data[model]['switches_per_match']
    all_turns = switch_data[model]['turns_per_match']

    total_switches = sum(all_switches)
    total_turns = sum(all_turns)
    num_matches = len(all_switches)

    switches_per_turn = total_switches / total_turns if total_turns > 0 else 0
    switches_per_match = total_switches / num_matches if num_matches > 0 else 0

    survivals = survival_data[model]
    avg_survival = sum(survivals) / len(survivals) if survivals else 0

    results.append({
        'Model': model,
        'Switches/Turn': f"{switches_per_turn:.2%}",
        'Switches/Match': f"{switches_per_match:.1f}",
        'Total Switches': total_switches,
        'Matches Played': num_matches,
        'Wins': len(survivals),
        'Avg Pokemon Remaining (Wins)': f"{avg_survival:.1f}"
    })

df_performance = pd.DataFrame(results)
display(Markdown("### Switching Behavior and Win Margins"))
display(df_performance)

# Token efficiency
def token_stats(tournament: Tournament) -> pd.DataFrame:
    """Analyze token usage per model."""
    from collections import defaultdict
    
    tokens = defaultdict(lambda: {'input': [], 'output': [], 'reasoning': [], 'latency': []})
    
    for match in tournament.matches:
        for player_id, log in match.player_logs.items():
            model = None
            for m in tournament.models:
                if m.lower().replace('-', '') in player_id.lower().replace('-', ''):
                    model = m
                    break
            if not model:
                continue
            
            for turn in log.turns:
                t = turn.tokens
                if t.get('input'):
                    tokens[model]['input'].append(t['input'])
                if t.get('output'):
                    tokens[model]['output'].append(t['output'])
                if t.get('reasoning'):
                    tokens[model]['reasoning'].append(t['reasoning'])
                if turn.latency_ms:
                    tokens[model]['latency'].append(turn.latency_ms)
    
    data = []
    for model in tournament.models:
        t = tokens[model]
        data.append({
            'Model': model,
            'Avg Input Tokens': f"{sum(t['input'])/len(t['input']):.0f}" if t['input'] else 'N/A',
            'Avg Output Tokens': f"{sum(t['output'])/len(t['output']):.0f}" if t['output'] else 'N/A',
            'Avg Reasoning Tokens': f"{sum(t['reasoning'])/len(t['reasoning']):.0f}" if t['reasoning'] else 'N/A',
            'Avg Latency (ms)': f"{sum(t['latency'])/len(t['latency']):.0f}" if t['latency'] else 'N/A'
        })
    
    return pd.DataFrame(data)

display(Markdown("### Token Usage & Latency"))
display(token_stats(tournament))